"""Initial Migrate

Revision ID: a7793911f7a0
Revises: 
Create Date: 2025-03-05 06:13:25.189455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7793911f7a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('till_number', sa.String(length=20), nullable=True),
    sa.Column('paybill_number', sa.String(length=20), nullable=True),
    sa.Column('pochi_number', sa.String(length=20), nullable=True),
    sa.Column('qr_code_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paybill_number'),
    sa.UniqueConstraint('pochi_number'),
    sa.UniqueConstraint('till_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MERCHANT', 'AGENT', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mpesa_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('store_number', sa.String(length=20), nullable=False),
    sa.Column('agent_number', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('qr_code_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_number'),
    sa.UniqueConstraint('store_number')
    )
    op.create_table('shop_managers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'shop_id')
    )
    op.create_table('qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('identity_type', sa.Enum('AGENT', 'TILL', 'PAYBILL', 'POCHI', name='qrcodeentitytype'), nullable=False),
    sa.Column('qr_code_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('merchant_till_id', sa.Integer(), nullable=True),
    sa.Column('merchant_paybill_id', sa.Integer(), nullable=True),
    sa.Column('merchant_pochi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['mpesa_agents.id'], ),
    sa.ForeignKeyConstraint(['merchant_paybill_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['merchant_pochi_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['merchant_till_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='transactionstatus'), nullable=False),
    sa.Column('transaction_type', sa.Enum('Withdrawal', 'Till Payment', 'Paybill Payment', 'Pochi Payment'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('customer_msisdn', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['mpesa_agents.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('qr_codes')
    op.drop_table('shop_managers')
    op.drop_table('mpesa_agents')
    op.drop_table('users')
    op.drop_table('merchants')
    # ### end Alembic commands ###
