"""empty message

Revision ID: dc8bcdcca1e4
Revises: d8feb010e6aa
Create Date: 2025-03-08 14:30:04.253052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8bcdcca1e4'
down_revision = 'd8feb010e6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.alter_column('identity_type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.alter_column('identity_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
